version: '3.8'

services:
  app:
    build: .
    container_name: nba-updates-container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - laravel-data:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - NBA_API_KEY=${NBA_API_KEY}

volumes:
  laravel-data:
