<?php

return [
    1 => 'hawks.svg',
    2 => 'celtics.svg',
    3 => 'nets.svg',
    4 => 'hornets.svg',
    5 => 'bulls.svg',
    6 => 'cavaliers.svg',
    7 => 'mavericks.svg',
    8 => 'nuggets.svg',
    9 => 'pistons.svg',
    10 => 'warriors.svg',
    11 => 'rockets.svg',
    12 => 'pacers.svg',
    13 => 'clippers.svg',
    14 => 'lakers.svg',
    15 => 'grizzlies.svg',
    16 => 'heat.svg',
    17 => 'bucks.svg',
    18 => 'timberwolves.svg',
    19 => 'pelicans.svg',
    20 => 'knicks.svg',
    21 => 'thunder.svg',
    22 => 'magic.svg',
    23 => '76ers.svg',
    24 => 'suns.svg',
    25 => 'blazers.svg',
    26 => 'kings.svg',
    27 => 'spurs.svg',
    28 => 'raptors.svg',
    29 => 'jazz.svg',
    30 => 'wizards.svg',
];
